# Autogenerated wrapper script for simdjson_jll for i686-linux-musl-cxx03
export libsimdjson

JLLWrappers.@generate_wrapper_header("simdjson")
JLLWrappers.@declare_library_product(libsimdjson, "libsimdjson.so.8")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsimdjson,
        "lib/libsimdjson.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
